---
# tasks file for ansible
- name: Update OS
  include_tasks: update_os.yml

- name: Install python3 and pip3
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Upgrade pip3
  command: pip3 install --upgrade pip
  changed_when: false

- name: Install ansible with version with pip3
  pip:
    name: ansible
    version: '{{ ansible_version }}'
    executable: pip3
