version: 2
jobs:
  test:
    machine:
      services: docker
    environment:
      - ROLE_NAME: ansible
    steps:
      - checkout
      - run:
          name: Install python and python-pip
          command: |
            sudo apt-get update -y
            sudo apt-get install python -y
            sudo apt-get install python-pip -y
            pip install --upgrade pip
          
      - run:
          name: Install dependencies
          command: |
            pip install docker==3.4.1
            pip install molecule ansible-lint yamllint
          
      - run:
          name: Test role with molecule
          command: |
            mkdir ~/ansible-role-$ROLE_NAME
            cd ..
            mv ~/project/{,.[^.]}* ~/ansible-role-$ROLE_NAME
            cd ~/ansible-role-$ROLE_NAME
            molecule test      
workflows:
  version: 2
  molecule:
    jobs:
      - test
